### ISSUE TITLE
Add a couple more gems

### ISSUE THREAD

**Issue by gvoicu** [ManuelFrigerio/rails-blueprint#1]
Hello @ManuelFrigerio,

Thank you for making time to do this blueprint, it's helpful for being able to quickly start developing a new project.

I was thinking maybe there could be added some more initial gems? I was thinking at: letter_opener, rubocop, and pry (together with pry-rails). I could add them if you agree.

What do you think?

**Comment by ManuelFrigerio** [comment]
That's a very good idea! Yes please, if you could open a PR it'd be great :)

**Comment by gvoicu** [comment]
Cool! Sure, I'll do it. 👍

**Comment by gvoicu** [comment]
@ManuelFrigerio I've came back with an improvement. Do you think we should add more gems to this? I was thinking maybe at: an admin gem ([ActiveAdmin](https://github.com/activeadmin/activeadmin) or [RailsAdmin](https://github.com/sferik/rails_admin)) and [DotEnv](https://github.com/bkeepers/dotenv).

What do you think about it?

**Comment by ManuelFrigerio** [comment]
@gvoicu I'd like to avoid adding too many gems. The risk is to add too much and making the boilerplate too heavy and difficult to customize. So for that reason, I'd avoid the admin gem (a lot of apps don't need one) whereas I like DotEnv (every app needs to store environment variables locally)

**Comment by gvoicu** [comment]
Ok, I'll add DotEnv then

**Comment by ManuelFrigerio** [comment]
Great. Can you also add a comment to the ReadMe about that?

**Comment by gvoicu** [comment]
Thanks for the merge, @ManuelFrigerio! It's ok if we close this issue?

**Comment by ManuelFrigerio** [comment]
Yep absolutely
